### ISSUE TITLE
Is it possible to make the onHandle in hooks.server.js a async function?

### ISSUE THREAD

**Issue by remi-freriks** [jill64/sentry-sveltekit-cloudflare#88]
For other modules I need to add await statements in the hooks.server.js. How do I make the onHandle function async?

**Comment by remi-freriks** [comment]
Thanks, this is how it works. Another question, do you have any idea why on dev still errors go to sentry even though I set enableInDevMode: false in the serverInit of hooks.server.js?

**Comment by jill64** [comment]
I am aware of this phenomenon as a bug, but have not been able to resolve it.
For the sake of transparency, I would like to Open the following Issue and begin addressing it.

Issue #91
